### ISSUE TITLE
backports and other approaches

### ISSUE THREAD

**Issue by maelle** [r-hub/blog#140]
e.g. https://www.mail-archive.com/r-package-devel@r-project.org/msg06331.html

**Comment by maelle** [comment]
it'd be interested to find, via pkgsearch, what R packages have a dependency on a given R version.

**Comment by maelle** [comment]
@Bisaloo has many interesting ideas on the topic

**Comment by Bisaloo** [comment]
Summary of our discussion from last year on this topic before I lose my notes:

## How to declare a dependency to a minimum R version and why you may need to do so?

https://www.mail-archive.com/r-package-devel@r-project.org/msg06331.html

## How to choose on which version you should depend?

Two different/opposed views:
- Historically, usethis automatically added a dependency to the current R version. Based on the idea this is the version it was tested on.
- Karthik in [this GH issue](https://github.com/ropensci/dev_guide/issues/185): "An example of bad practice would be for a developer to consider the versions of their current state of dependencies to be the min. That would needlessly force everyone to upgrade (causing issues with other packages) when there is no good reason behind that version choice."

usethis seems to have changed their policy and it would be interesting to find where/when it happened and if they explained the rationale behind this change.

You will have to indirectly depend on a minimum version due to your other dependency so you might as well enjoy it and not restrict yourself to older versions than your dependencies.

Keep in mind that it might be difficult for users to access recent R versions in environments where they don't have admin rights.

## Statistics on CRAN packages

- pkgsearch

But it's almost sure that some of them are wrong and depend on a more recent version than what they're claiming. This happens because CRAN automated checks only happen with R release, devel and oldrel, not with older R versions. [In this SO comment](https://stackoverflow.com/questions/38686427/determine-minimum-r-version-for-all-package-dependencies#comment64752971_38686427), Bob Rudis mentions the case of rodham. There is [another example with rgl on R-pkg-devel](https://stat.ethz.ch/pipermail/r-package-devel/2021q1/006508.html).

It should possible to perform some analysis of CRAN to automatically detect if some packages actually depend on newer version than what they claim. Based on regexes of functions in backports? It would cause a lot of false positives. Based on R CMD check in older R versions? Very computationally heavy.
It is even harder if you take into account not just new functions in base R but breaking changes in older functions (e.g., new `recycle0` argument introduced in `paste()`).
That would be super interesting to have in this post but is it realistic?

## How to avoid depending on a new version?

backports

## How to test you depend on the correct version?

GitHub Actions. Cannot go further back than R 3.3 because rcmdcheck uses digest, which depends on R 3.3. It might be possible to manually craft an action which uses R CMD check directly but it's getting more difficult.

**Comment by maelle** [comment]
Noting one cannot use backports for the native pipe

**Comment by maelle** [comment]
Noting one cannot use backports for the native pipe

**Comment by Bisaloo** [comment]
This seems related & useful:

https://lintr.r-lib.org/reference/backport_linter.html

**Comment by maelle** [comment]
Fixed in #156
