### ISSUE TITLE
How to add comments

### ISSUE THREAD

**Issue by maelle** [r-hub/blog#19]
Interesting thread about Disqus & alternatives 

https://twitter.com/hrbrmstr/status/1135915244532822018?s=19

**Comment by gaborcsardi** [comment]
The GH issue widget is pretty cool.

**Comment by maelle** [comment]
That's my favourite solution too, so I'll work on that. :smile_cat:

**Comment by maelle** [comment]
So easy to add, so cool.

**Comment by VincentTam** [comment]
Hi, this is the maintainer of @staticmanlab, a public GitLab instance of Staicman. While GH issue supports GitHub only, Staticman supports both GitHub & GitLab.

Staticman makes use of GitHub/GitLab Pull/Merge Requests instead of issues. Under Staticman's model, static comments are YML/JSON files stored in the remote GitHub/GitLab repo (usually under data/comments, configurable through the path parameter in root-level staticman.yml), and through a static blog generator (Jekyll/Hugo/etc), the stored data are rendered as part of the content. This gives a total ownership of a static site's comments, apart from improving the site's SEO.
