### ISSUE TITLE
Link for Alicia's talk in "Code gen. in R pkgs" post?

### ISSUE THREAD

**Issue by batpigandme** [r-hub/blog#71]
Currently the link on the line below goes to vlbuilder on GitHub. This might be what you want (I didn't get to see Alicia's talk ☹️). There is a link to her slides from the conference [here](https://docs.google.com/presentation/d/e/2PACX-1vRUDiM3DaPjYP5b1BafSraf8GWwJk_jy6YV_l9lZgeBVwKDSfqiHcTn8M-Qm-6U7frMX7SLqQthJxah/pub?start=false&loop=false&delayms=3000#slide=id.p), or you might be waiting for the conf. talks to go up!
https://github.com/r-hub/blog/blob/7cf5f4584e4ffbc349ef853ca7bfb087a869924d/content/post/2020-02-10-code-generation/index.Rmd#L23

**Comment by maelle** [comment]
Thank you! Yes I'm waiting for the talks to go up but this issue will serve as a reminder so that's perfect. :hourglass_flowing_sand:  In her slides Alicia gave a link to the vlbuilder README, whose first paragraph mentioned the slides. "For some background and context on the package you can check out slides from a rstudio::conf talk in January 2020."

For info I watched the talk by using [@milesmcbain's hack](https://twitter.com/MilesMcBain/status/1223759922875121664) because I couldn't wait for the actual recording. :grin:
